services:

{% if cookiecutter.api_mock == "mirageJS" %}
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      VITE_API_MOCK: true
      VITE_API_BASE_URL: /
      VITE_NODE_ENV: development

{% else %}
  frontend:
    depends_on:
      - apimock
      - nginx

  apimock:
    build:
      context: ./apimock
    image: apimock-{{cookiecutter.project_slug}}
    container_name: apimock-{{cookiecutter.project_slug}}
    hostname: apimock-{{cookiecutter.project_slug}}
    command: npm run apimock:watch
    network_mode: "host"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./apimock/server:/apimock/server
{% endif %}