name: Deploy to Fly.io

on:
  workflow_run:
    workflows:
      - {{cookiecutter.project_slug}} CI
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: {%raw%}${{ secrets.FLY_API_TOKEN }}{%endraw%}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
    environment:
      name: production
      url: https://{{cookiecutter.deploy_domain}}
